FROM ubuntu:14.04

MAINTAINER gracjan@man.poznan.pl


RUN echo "deb http://ppa.launchpad.net/openjdk-r/ppa/ubuntu trusty main" >> /etc/apt/sources.list && \
	echo "deb-src http://ppa.launchpad.net/openjdk-r/ppa/ubuntu trusty main" >> /etc/apt/sources.list && \
	apt-get update && \
	apt-get --force-yes install -y openjdk-8-jdk && \
	apt-get install -y maven git curl && \
	git clone https://github.com/indigo-dc/cdmi-spi.git && \
	cd cdmi-spi && \
	mvn install && \
	cd .. && \
	git clone https://github.com/indigo-dc/CDMI.git && \
	cd CDMI && \
	echo "java -Djava.security.egd=file:/dev/./urandom -jar target/cdmi-server-0.1-SNAPSHOT.jar  --server.port=8080" > run.sh && \
	chmod +x run.sh && \	
	mvn package -Dmaven.test.skip=true

WORKDIR /CDMI

#ENTRYPOINT java -Djava.security.egd=file:/dev/./urandom -jar target/cdmi-server-0.1-SNAPSHOT.jar
#CMD java -jar target/cdmi-server-0.1-SNAPSHOT.jar

# cdmi-spi commit id
#git checkout caedabb && \

# CDMI commit id
#git checkout f931402 && \