#
# Image pre-configured to test fork of CDMI server which adds persistence to embedded redis db
# cdmi-s3-qos module is preconfigured to "life-mode", credential to CEPH node has to be set up
# after first run of container
#
FROM ubuntu:14.04

MAINTAINER gracjan@man.poznan.pl

# it is only to get access to /cdmi-s3-qos/templates/springboot/config/application.yml
# this file configures connection to redis server  
COPY . /cdmi-s3-qos

RUN echo "deb http://ppa.launchpad.net/openjdk-r/ppa/ubuntu trusty main" >> /etc/apt/sources.list && \
	echo "deb-src http://ppa.launchpad.net/openjdk-r/ppa/ubuntu trusty main" >> /etc/apt/sources.list && \
	apt-get update && \
	apt-get --force-yes install -y openjdk-8-jdk && \
	apt-get install -y maven git curl redis-tools vim && \
	git clone https://github.com/indigo-dc/cdmi-spi.git && \
	cd cdmi-spi && \
	git checkout 36107fe && \
	mvn install && \
	cd .. && \
    cd cdmi-s3-qos && \
    git checkout redis_dev && \
    mvn install && \
    cd .. && \
	git clone https://github.com/komputerowiec/CDMI.git && \
	cp -rf cdmi-s3-qos/config CDMI/ && \
	rm -f CDMI/config/objectstore.properties && \
	echo "objectstore.backend-gateway=org.indigo.cdmi.backend.radosgw.LifeModeBackendGateway" > CDMI/config/objectstore.properties && \
	echo "objectstore.ssh-gateway.host=<OBJECT STORE GATEWAY IP>" >> CDMI/config/objectstore.properties && \
	echo "objectstore.ssh-gateway.user=<USERNAME>" >> CDMI/config/objectstore.properties && \ 
	echo "objectstore.ssh-gateway.password=<PASSWORD>" >> CDMI/config/objectstore.properties && \
	cd CDMI && \
	git checkout efb89a1 && \
	cp -r ../cdmi-s3-qos/templates/springboot/config/application.yml config/application.yml && \
	sed -i 's/dummy_filesystem/radosgw/g' config/application.yml && \
	sed -i 's/filesystem/radosgw/g' config/application.yml && \
	sed -i 's/<dependencies>/<dependencies>\r\n<dependency>\r\n<groupId>pl.psnc<\/groupId>\r\n<artifactId>cdmi-s3-qos<\/artifactId>\r\n<version>0.0.1-SNAPSHOT<\/version>\r\n<\/dependency>/g' pom.xml && \
	sed -i 's/active: redis/active: redis-embedded/g' config/application.yml && \
	echo "java -Djava.security.egd=file:/dev/./urandom -jar target/cdmi-server-0.1-SNAPSHOT.jar  --server.port=8080" > run.sh && \
	chmod +x run.sh && \	
	mvn package -Dmaven.test.skip=true

WORKDIR /CDMI

#ENTRYPOINT java -Djava.security.egd=file:/dev/./urandom -jar target/cdmi-server-0.1-SNAPSHOT.jar
#CMD java -Djava.security.egd=file:/dev/./urandom -jar target/cdmi-server-0.1-SNAPSHOT.jar  --server.port=8080
