#
# Image pre-configured for tests of cdmi-s3-qos in fixed-mode. 
# 
FROM ubuntu:14.04

MAINTAINER gracjan@man.poznan.pl

COPY . /cdmi-s3-qos

RUN echo "deb http://ppa.launchpad.net/openjdk-r/ppa/ubuntu trusty main" >> /etc/apt/sources.list && \
	echo "deb-src http://ppa.launchpad.net/openjdk-r/ppa/ubuntu trusty main" >> /etc/apt/sources.list && \
	apt-get update && \
	apt-get --force-yes install -y openjdk-8-jdk && \
	apt-get install -y maven git curl redis-tools rsync dos2unix vim && \
	cd cdmi-s3-qos && \
	mvn -Dmaven.test.skip=true install && \
	cd .. && \
	git clone https://github.com/indigo-dc/CDMI.git && \
	cp -rf cdmi-s3-qos/config CDMI/ && \
	cp -f cdmi-s3-qos/test/objectstore.properties CDMI/config/ && \
	rsync --ignore-times --ignore-errors cdmi-s3-qos/templates/local/objectstore.properties CDMI/config/ || test 1 && \
	cd CDMI && \
	#git checkout c6c1178 && \
	git checkout 70549a4 && \ 
	sed -i 's/dummy_filesystem/radosgw/g' config/application.yml && \
	sed -i 's/active: redis/active: redis-embedded/g' config/application.yml && \
	sed -i 's/<dependencies>/<dependencies>\r\n<dependency>\r\n<groupId>pl.psnc<\/groupId>\r\n<artifactId>cdmi-s3-qos<\/artifactId>\r\n<version>2.0.0-SNAPSHOT<\/version>\r\n<\/dependency>/g' pom.xml && \
	echo "java -Djava.security.egd=file:/dev/./urandom -jar target/cdmi-server-1.2.jar  --server.port=8080" > run.sh && \
	echo "java -Xdebug -Xrunjdwp:transport=dt_socket,server=y,address=8765 -Djava.security.egd=file:/dev/./urandom -jar target/cdmi-server-1.2.jar  --server.port=8080" > debug.sh && \
	chmod +x debug.sh && \
	chmod +x run.sh && \
	mvn package -Dmaven.test.skip=true

WORKDIR /CDMI

#ENTRYPOINT java -Djava.security.egd=file:/dev/./urandom -jar target/cdmi-server-0.1-SNAPSHOT.jar --server.port=8080
#CMD java -jar target/cdmi-server-0.1-SNAPSHOT.jar
