FROM centos:7

MAINTAINER gracjan@man.poznan.pl

COPY . /cdmi-s3-qos

WORKDIR /root



RUN yum update -y && \
	yum install git curl mc java-1.8.0-openjdk net-tools epel-release -y && \
	yum update -y && \
	yum install ansible -y && \
	cp /cdmi-s3-qos/templates/ansible/* . && \
	chmod -x playbook inventory && \
	mkdir roles && \
	cd roles && \
	git clone https://github.com/indigo-dc/ansible-role-cdmi-s3-qos.git cdmi-s3-qos && \
	cd cdmi-s3-qos && \
	git checkout devel
	


#RUN	apt-get update && \
#	apt-get install -y git curl vim wget software-properties-common && \
#	apt-add-repository -y ppa:ansible/ansible && \
#	apt-get update && \
#	apt-get install -y ansible python-apt python-pycurl && \ 
#	cp /cdmi-s3-qos/templates/ansible/* . && \
#	chmod -x playbook inventory && \
#	mkdir roles && \
#	cd roles && \
#	git clone https://github.com/indigo-dc/ansible-role-cdmi-s3-qos.git cdmi-s3-qos && \
#	cd cdmi-s3-qos && \
#	git checkout devel
