#
# Image with automated integrations tests.
# Components:
# - cdmi server with embedded redis server 
# - cdmi-s3-qos in fixed-mode
#
#
# Image pre-configured to test CDMI server with default (embedded) implementation of StorageBacked interface (default QoS module).
# redis in embedded mode
#
FROM ubuntu:14.04

MAINTAINER gracjan@man.poznan.pl

# it is only to get access to /cdmi-s3-qos/templates/springboot/config/application.yml
# this file configures connection to redis server
COPY . /cdmi-s3-qos

RUN echo "deb http://ppa.launchpad.net/openjdk-r/ppa/ubuntu trusty main" >> /etc/apt/sources.list && \
        echo "deb-src http://ppa.launchpad.net/openjdk-r/ppa/ubuntu trusty main" >> /etc/apt/sources.list && \
        apt-get update && \
        apt-get --force-yes install -y openjdk-8-jdk && \
        apt-get install -y maven git curl redis-tools && \
        git clone https://github.com/indigo-dc/cdmi-spi.git && \
        cd cdmi-spi && \
        git checkout 9c7480e && \
        mvn install && \
        cd .. && \
    cd cdmi-s3-qos && \
    mvn install && \
    cd .. && \
        git clone https://github.com/indigo-dc/CDMI.git && \
        cd CDMI && \
        git checkout ec4bfce && \
        cp -rf ../cdmi-s3-qos/config . && \
        cp -r ../cdmi-s3-qos/templates/springboot/config/application.yml config/application.yml && \
        cp ../cdmi-s3-qos/templates/integration-tests/launch-integration-tests.sh . && \
        chmod +x launch-integration-tests.sh && \
        sed -i 's/<dependencies>/<dependencies>\r\n<dependency>\r\n<groupId>pl.psnc<\/groupId>\r\n<artifactId>cdmi-s3-qos<\/artifactId>\r\n<version>0.0.1-SNAPSHOT<\/version>\r\n<\/dependency>/g' pom.xml && \
        sed -i 's/dummy_filesystem/radosgw/g' config/application.yml && \
        sed -i 's/active: redis/active: redis-embedded/g' config/application.yml && \
        echo "java -Djava.security.egd=file:/dev/./urandom -jar target/cdmi-server-1.1.jar  --server.port=8080" > run.sh && \
        chmod +x run.sh && \
        mvn package -Dmaven.test.skip=true

WORKDIR /CDMI


#ENTRYPOINT java -Djava.security.egd=file:/dev/./urandom -jar target/cdmi-server-1.1.jar
#CMD java -Djava.security.egd=file:/dev/./urandom -jar target/cdmi-server-1.1.jar  --server.port=8080
