#
# Image pre-configured to test CDMI server with real CEPH on back-end,
# NOTE: Before first run, the CEPH account configuration file has to be placed in 
# config/objectstore.properties
#
# To be executed/used through docker-compose (docker-compose-life-ex-redis.yml)
#
FROM ubuntu:14.04

MAINTAINER gracjan@man.poznan.pl

# it is only to get access to /cdmi-s3-qos/templates/springboot/config/application.yml
# this file configures connection to redis server  
COPY . /cdmi-s3-qos
#COPY CDMI /CDMI

RUN echo "deb http://ppa.launchpad.net/openjdk-r/ppa/ubuntu trusty main" >> /etc/apt/sources.list && \
	echo "deb-src http://ppa.launchpad.net/openjdk-r/ppa/ubuntu trusty main" >> /etc/apt/sources.list && \
	apt-get update && \
	apt-get --force-yes install -y openjdk-8-jdk && \
	apt-get install -y maven git curl redis-tools && \
	git clone https://github.com/indigo-dc/cdmi-spi.git && \
	cd cdmi-spi && \
	git checkout 67b6d7b && \
	mvn install && \
	cd .. && \
    cd cdmi-s3-qos && \
    mvn install && \
    cd .. && \
	git clone https://github.com/indigo-dc/CDMI.git && \
	#cp -rf cdmi-s3-qos/config CDMI/ && \
	rm -f CDMI/config/objectstore.properties && \
	cd CDMI && \
	git checkout 59bef6d && \
	cp -rf ../cdmi-s3-qos/config . && \
	ls -l ../cdmi-s3-qos/config > /tmp/raz.log && \
	ls -l  config > /tmp/dwa.log && \
	cp -r ../cdmi-s3-qos/templates/springboot/config/application.yml config/application.yml && \
	sed -i 's/dummy_filesystem/radosgw/g' config/application.yml && \
	sed -i 's/<dependencies>/<dependencies>\r\n<dependency>\r\n<groupId>pl.psnc<\/groupId>\r\n<artifactId>cdmi-s3-qos<\/artifactId>\r\n<version>0.0.1-SNAPSHOT<\/version>\r\n<\/dependency>/g' pom.xml && \
	echo "java -Djava.security.egd=file:/dev/./urandom -jar target/cdmi-server-1.1.jar  --server.port=8080" > run.sh && \
	chmod +x run.sh && \	
	mvn package -Dmaven.test.skip=true && \
	echo "curl -X PUT http://restadmin:restadmin@localhost:8080/standard -H \"Content-Type: application/cdmi-container\" -d '{}'" >> create-cdmi-containers.sh && \
	echo "curl -X PUT http://restadmin:restadmin@localhost:8080/silver -H \"Content-Type: application/cdmi-container\" -d '{}'" >> create-cdmi-containers.sh && \
	echo "curl -X PUT http://restadmin:restadmin@localhost:8080/golden -H \"Content-Type: application/cdmi-container\" -d '{}'"  >> create-cdmi-containers.sh && \
	chmod +x create-cdmi-containers.sh 
	

WORKDIR /CDMI

#ENTRYPOINT java -Djava.security.egd=file:/dev/./urandom -jar target/cdmi-server-0.1-SNAPSHOT.jar
#CMD java -jar target/cdmi-server-0.1-SNAPSHOT.jar
CMD java -Djava.security.egd=file:/dev/./urandom -jar target/cdmi-server-1.1.jar --server.port=8080

